# ASCII-Font › https://patorjk.com/software/taag/#p=display&f=Big&t=Friends+of%0AColden+%0AClough
#
#  ______    _                _              __ 
# |  ____|  (_)              | |            / _|
# | |__ _ __ _  ___ _ __   __| |___    ___ | |_ 
# |  __| '__| |/ _ \ '_ \ / _` / __|  / _ \|  _|
# | |  | |  | |  __/ | | | (_| \__ \ | (_) | |  
# |_|__|_|  |_|\___|_| |_|\__,_|___/  \___/|_|  
#  / ____|    | |   | |                         
# | |     ___ | | __| | ___ _ __                
# | |    / _ \| |/ _` |/ _ \ '_ \               
# | |___| (_) | | (_| |  __/ | | |              
#  \_____\___/|_|\__,_|\___|_|_|_|              
#  / ____| |                 | |                
# | |    | | ___  _   _  __ _| |__              
# | |    | |/ _ \| | | |/ _` | '_ \             
# | |____| | (_) | |_| | (_| | | | |            
#  \_____|_|\___/ \__,_|\__, |_| |_|            
#                        __/ |                  
#                       |___/                   
#
# Title of the website
title: Friends of Colden Clough
# The description is used on homepage and in the footer to quickly describe the website.
# Use a maximum of 150 characters for SEO-purposes.
description: A friendly community volunteer group carrying out nature restoration work in the ancient woodland of Colden Clough
# This URL is the main address. Don't include a slash at the end.
url: "https://friendsofcoldenclough.org.uk"
host: localhost
port: 4000
# The baseurl is the subdirectory of your site, e.g. /blog or /
baseurl: ""
# admin email address
admin_email: "info@friendsofcoldenclough.org.uk"
# URL path to images directory
imgpath: "/assets/images/"

# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: pygments
excerpt_separator: <!--more-->
future: true

# The language setting is used in /includes/header.html for html-settings
language: "en"

# SASS processing settings
sass:
    sass_dir: _scss
    style: compressed

# SEO shit
# google_author:             ""
# google_site_verification:  ""
# bing_webmastertools_id:    ""
# alexa_verify_id:           ""

# Social Media bollocks
facebook: "https://www.facebook.com/groups/3797294470486573/"

# Include/exclude files from production _site
exclude:
- node_modules
- Gemfile
- Gemfile.lock
- package.json
- package-lock.json
- LICENSE
- README.md
- CNAME
